### ISSUE TITLE
Feedback Request:Containers

### ISSUE THREAD

**Issue by Tjomba1996** [TechGrounds-Cloud8/cloud8-Tjomba1996#45]
**Feedback Request: Containers**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Tjomba1996/blob/main/05_Azure/Containers.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
Well done!

**Comment by benbui797** [comment]
Looks good!
IIRC you mentioned Microservices in a previous assignment? If that is true, it would have been nice to see that return here :)
That would also make your "Why" part a bit more extensive, because IMO there is more to containers than portability and ease of deployment

**Comment by yismailmo** [comment]
well summarized, but i'm missing how you can combine containers with other services.
