### ISSUE TITLE
Feedback Request: Azure Support Plans

### ISSUE THREAD

**Issue by Tjomba1996** [TechGrounds-Cloud8/cloud8-Tjomba1996#46]
**Feedback Request Azure Support Plans**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Tjomba1996/blob/main/05_Azure/Azure%20Support%20Plans.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
At the ''_Azure provides 4 different tier of support plan_:'' you forgot the fourth one,Professional direct.

_Standard: Around €93,- a month, provides 24/7 technical support Below is a schematic a_ een spatie hier en een andere regel vanaf Below.
