### ISSUE TITLE
Feedback Request: Azure Advisor

### ISSUE THREAD

**Issue by Tjomba1996** [TechGrounds-Cloud8/cloud8-Tjomba1996#47]
**Feedback Request Azure Advisor**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Tjomba1996/blob/main/05_Azure/Azure%20Advisor.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
typo: AWS can provide a similar _services_..

Voor de rest ziet er goed uit.

**Comment by yismailmo** [comment]
Well summarized, just a small typo "see if they are being used properly, and _in_ they aren't"
